### ISSUE TITLE
Two windows with two imgui contexts causes an assert

### ISSUE THREAD

**Issue by CatsNipYummy** [pyimgui/pyimgui#137]
I have two windows using glfw and that works fine and I am able to have a simple OpenGL rendering on both windows. But when I add the imgui to it, it crashes with the following assert when I call imgui.new_frame():

`imgui.core.ImGuiError: ImGui assertion error (g.IO.DisplaySize.x >= 0.0f && g.IO.DisplaySize.y >= 0.0f && "Invalid DisplaySize value") at imgui-cpp/imgui.cpp:3090`

I checked the values of `imgui.get_io().display_size` and I get the right values there (1920, 1080).
I am switching between the two glfw and imgui context using `glfw.make_context_current(each_window)` and `make_context_current(each_imgui_context)`. Is there anything else I need to do to prevent this assert?

**Comment by swistakm** [comment]
Could you provide some minimal example of code with this error occurring? It would make easier to understand what we are dealing with here.

**Comment by pbuckner** [comment]
This appears to be due to using global `_io` in core.pyx `get_io()`. The IO is cached, but not altered if/when context is changed.  If instead one simply rewrites as:

```
def get_io():
   return _IO()
```

It won't complain about DisplaySize and you'll be able to continue.

Though, I have to assume the `global _io` was put in the code for good reason, so there may be other issues.

**Comment by pbuckner** [comment]
Attached is small modification to doc/examples/integratins_glfw3.py

It creates multiple windows (each with imgui.show_test_windows()) With "current" imgui.get_io() it results in ImGui assertion error about DisplaySize (as mentioned above). Execute with "1" window, it works fine. Execute with more than one window you get assertion.

Make the simple change to imgui.get_io() as I suggested in previous message, any number of windows will work.

[integrations_glfw3.py.zip](https://github.com/swistakm/pyimgui/files/6087142/integrations_glfw3.py.zip)

**Comment by pbuckner** [comment]
So, can we get away with simply calling `return _IO()` for every call to `get_io()`? 

I think so. For the most part. `class _IO()` simply defines getters and setters, manipulating the underlying value based on cimgui.GetIO -- that is, `self._ptr`. 

So a change in context changes the underlying cimgui.GetIO(), so a new imgui.get_io() builds the python interface around the (then current) context.

The _only_ question I have would be with respect to _set_clipboard_text() and related clipboard methods of _IO(). It would appear that each call to _IO() is nondestructive with the exception of _io.get_clipboard_text_fn and _io.set_clipboard_text_fn. That is, if I were to set the clipboard function in one context, switch contexts & then switch back to the first context, I'd lose my get_clipboard_text_fun (and set...)

The levels of indirection w.r.t. these clipboard functions makes my head spin: Is there test code for clipboards?
