### ISSUE TITLE
How to build a whl for windows platform?

### ISSUE THREAD

**Issue by mebman101** [pyimgui/pyimgui#239]
Hi, I want to build a wheel file for a project I'm working on. 
I have successfully managed to run an example file from the source. Now I want to use the source in a separate project.
I'm using imgui v1.84 with docking feature. 
I'm a beginner in python. I don't know what to do after successfully building the source.

**Comment by gotohelli789** [comment]
![pyimgui](https://user-images.githubusercontent.com/25292894/127777273-07023829-1aef-4ffa-8e67-3a50c2a27a9c.PNG)
The docking branch is working fine with all the features.
I used https://github.com/KinoxKlark/pyimgui/tree/upgrade/v1.79 and modified it a bit. Added the imgui 1..84 docking in `imgui-cpp` folder of the source code

**Comment by mebman101** [comment]
Nevermind, I figured it out myself. I am building it with AppVeyor.
