### ISSUE TITLE
typo CONFIG_NO_MOUSE_CURSOR_CHARGE remains in pyglet integration

### ISSUE THREAD

**Issue by connorjak** [pyimgui/pyimgui#243]
Looks like CI didn't catch this; https://github.com/pyimgui/pyimgui/blob/9e97c2489fc7f424d7df63fd9a13df770ceacffe/imgui/integrations/pyglet.py#L108 (current master) still has the typo. This breaks pyglet-based pyimgui apps.

_Originally posted by @connorjak in https://github.com/pyimgui/pyimgui/issues/216#issuecomment-956383441_

**Comment by KinoxKlark** [comment]
Good catch, thanks!
I fixed it in commit https://github.com/pyimgui/pyimgui/commit/a5edd386ee50ab6dd515256cca542223fdf2d0bd. I did a search in all files to be sure. I'll wait until the end of the week to wait if any other issues with the latest release occurs and I'll push a minor release with all fixes (1.4.1).

**Comment by connorjak** [comment]
I fixed it locally in my `site_packages` and verified it worked.

Also, ideally, we would have a test in the CI that would have caught this. Not this particular issue, but it would "exercise" the pyglet integration and see if anything failed.
