### ISSUE TITLE
Is there a way to set the allocator functions as in c++ ?

### ISSUE THREAD

**Issue by Zakariya-H** [pyimgui/pyimgui#246]
I want to achieve something like ```ImGui::GetAllocatorFunctions(alloc_func, free_func, &user_data)```

**Comment by KinoxKlark** [comment]
Thanks for reaching. Unfortunately no, I don't think there is. At least not for now. `SetAllocatorFunctions()`, `GetAllocatorFunctions()`, `MemAlloc()`, and `MemFree()` are not mapped. If you have a good implementation suggestion or use case you can propose it in the dev-2.0 branch as a pull request!

**Comment by Zakariya-H** [comment]
Ok thank you !
