### ISSUE TITLE
Intellisense?

### ISSUE THREAD

**Issue by ItsCubeTime** [pyimgui/pyimgui#269]
Is it possible to get auto completion for all the members of the imgui module?

![image](https://user-images.githubusercontent.com/20190653/158037037-11588906-1dde-4900-b5b3-a7a1accb282d.png)
VS Codes Microsoft Python extension doesnt seem to recognize any symbols

**Comment by KinoxKlark** [comment]
Thanks to @masc-it this should be possible using his public interface extraction script #263. I didn't test it yet but it seems to be what you are looking for. 

As a user of `intellisense`, is it something you would expect to find distributed in this repo? Do you know if we should compile a `*.pyi` ourselves and distribute it with `pip`, would this be sufficient to activate the functionality for our users?

**Comment by ItsCubeTime** [comment]
> As a user of `intellisense`, is it something you would expect to find distributed in this repo? Do you know if we should compile a `*.pyi` ourselves and distribute it with `pip`, would this be sufficient to activate the functionality for our users?
Yes absolutely you should! Especially as the docummentation appears quite sparse & doesnt seem to cover al lfeatures. Im finding myself reading your source code rn to figure out what to do

**Comment by ItsCubeTime** [comment]
I hope it isnt missing anything
https://user-images.githubusercontent.com/20190653/158054709-35882140-21dd-422e-a59f-2a9beaffa98e.mp4

**Comment by KinoxKlark** [comment]
Thanks for your feedback, I'll consider shipping this with future releases.

I close the issue, feel free to re-open it if you think I missed something that needed to be addressed.
