### ISSUE TITLE
Is it possible to integrate `pyimgui` with Pygame?

### ISSUE THREAD

**Issue by TechStudent10** [pyimgui/pyimgui#288]
I've seen that you can install a `pygame` backend for Imgui, but I can't find anything that shows that you can integrate directly with Pygame.

Is this possible?

**Comment by TechStudent10** [comment]
Ah after digging into the docs, I've found this example: https://github.com/pyimgui/pyimgui/blob/master/doc/examples/integrations_pygame.py.

**Comment by KinoxKlark** [comment]
Yes indeed, you can look at examples in `/doc/examples/...` as you figured out.

May I suggest you use the branch `dev/version-2.0` if you don't use it already. It proposes a lot more functionalities, and it uses a "recent" version of DearImgui. It should be stable enough, and any feedback would be welcome :)

**Comment by TechStudent10** [comment]
> May I suggest you use the branch `dev/version-2.0` if you don't use it already.

Just got it installed.

> It should be stable enough, and any feedback would be welcome :)

Alright!
