### ISSUE TITLE
Example to fix windows inside a viewport : GLFW

### ISSUE THREAD

**Issue by rohit-kumar-j** [pyimgui/pyimgui#298]
Is there an example to fix a window inside a viewport for glfw? and cursor tracking is `XOR` type in that viewport?

Example:
The Imgui window is locked in position?

![image](https://user-images.githubusercontent.com/37873142/191754327-04ca9ac4-d4dd-47a5-8822-0ed71500ac3c.png)

**Comment by learn-more** [comment]
Your request about fixing a window in one position seems to be completely unrelated to GLFW?

**Comment by rohit-kumar-j** [comment]
@learn-more, I'm not so sure(that is partly why I am asking this). When using [mujoco-python-viewer](https://github.com/rohit-kumar-j/mujoco-python-viewer) , I use viewports inside the window something like this:
```
graph_viewport= mujoco.MjrRect(
            int(3 * width / 4) + width_adjustment,
            0,
            int(window_width / 4),
            int(window_height / 4),) 

```
This keeps the the location static w.r.t the window
However, I do not know what the underlying `MjrRect` function does as it renders the graph inside the viewport. 

I expected there to be method to lock the position of imgui inside the viewport(or even the window) or keep it locked to the side and the top of the window.

**Comment by swenninger-1** [comment]
Hi,

imgui provides methods for setting the position of the next window:

https://github.com/pyimgui/pyimgui/blob/74c359702542c4319f4541bab6825597991e980a/imgui/core.pyx#L2651-L2676

Does this provide the functionality you need?

You can also check the examples provided by pyimgui for some use cases:

https://github.com/pyimgui/pyimgui/blob/master/doc/examples/testwindow.py

Best regards
Stephan

**Comment by swenninger-1** [comment]
To answer these kind of questions you should familiarize yourself with the imgui library. Here is an FAQ, that addresses some of your questions already:

https://github.com/ocornut/imgui/blob/master/docs/FAQ.md

Also the C++ [imgui_demo](https://github.com/ocornut/imgui/blob/master/imgui_demo.cpp) provides a lot of examples on how to use the imgui API.

**Comment by learn-more** [comment]
@rohit-kumar-j This seems more like you want people to read the documentation for you and give you the exact code that you should use.
I suggest that you spend some time reading the documentation yourself.
