### ISSUE TITLE
Holp Can Add support for UE4

### ISSUE THREAD

**Issue by marshal-it** [pyimgui/pyimgui#300]

**Comment by learn-more** [comment]
What problem does this solve?
I don't see any gains of using a full-blown game engine as window manager to be honest....

**Comment by KinoxKlark** [comment]
I agree with @learn-more, I don't see any obvious gain of adding UE4 as a backend. Note however that pyimgui does not limit you in the choice of backends. We propose several implementation of different backends as examples, but you should be able to us it with any backend you like, even if not proposed with the library.

Thus, if you need to use UE4 as a window manager, you should be able to make it appends yourself. You can look at the proposed implementation to get inspired. (Note that the original cpp version of the library may be more appropriate if you want to use unreal engine).
