### ISSUE TITLE
A bug is albe to fix easily in \doc\examples\testwindow.py

### ISSUE THREAD

**Issue by EagleEatApple** [pyimgui/pyimgui#340]
I found a bug in \doc\examples\testwindow.py.
The line was 1733, and it used "imgui.COLOR_EDIT_HSV", but now in pyimgui, it should be "imgui.COLOR_EDIT_DISPLAY_HSV".
Please fix it.

Thanks,
Eagle

**Comment by KinoxKlark** [comment]
This should be fixed by #346 in branch `fixes`.
