### ISSUE TITLE
text_input restores previous value

### ISSUE THREAD

**Issue by Darkratos** [pyimgui/pyimgui#344]
Hello!

I'm currently trying to do a "placeholder" for a text input, but when setting the current text to an empty string it restores the placeholder value. Here's an example:

```
pop_textbox = False

if self.search_text == "Search or start a new chat":
    imgui.push_style_color( imgui.COLOR_TEXT, 0.7, 0.7, 0.7 )
    pop_textbox = True

imgui.set_next_item_width( 200 )
changed, temp = imgui.input_text( '#search-input', self.search_text )

if imgui.is_item_focused( ):
    self.search_text = ""

if pop_textbox:
    imgui.pop_style_color( )
```

If there's a fix or workaround to this, it'd be highly appreciated. Thanks!

**Comment by Darkratos** [comment]
> `changed, temp = imgui.input_text( '#search-input', self.search_text )` Should be: `changed, self.search_text = imgui.input_text( '#search-input', self.search_text )`

Yeah, I did that too. I found a really "hacky" way to do it.
Basically, if the input is focused and the text is the placeholder, I then create another input and set the focus to it.
The next frame I restore the focus to the original input. If the framerate is high enough it's not perceptible, but it's not the best way to do it. I think clearing the _input_text_shared_buffer before doing strcpy should resolve the issue.

My current "working" code:
```py
if self.restore_focus:
    imgui.set_keyboard_focus_here( )
    self.restore_focus = False

changed, self.search_text = imgui.input_text( '', self.search_text )

if imgui.is_item_focused( ) and self.search_text == "Search or start a new chat":
    self.search_text = ""
    imgui.set_keyboard_focus_here( )
    imgui.input_text( '###temp', '' )
    self.restore_focus = True

elif not imgui.is_item_focused( ) and self.search_text == "":
    self.search_text = "Search or start a new chat"
```

**Comment by Aman-Anas** [comment]
AFAIK you don't want to use an empty string for the name of your input text field
```python
changed, self.search_text = imgui.input_text( '', self.search_text )
``` 
because it can easily conflict with other imgui components. Instead, use ## so

```python
changed, self.search_text = imgui.input_text( '##search_text_field', self.search_text )
```

The way I usually do placeholder text is by defining the var during init, so

```python
def __init__(self):
    self.potato = "hello there"

def draw(self):
    ... # initialize window and stuff bla bla
        changed, self.potato= imgui.input_text( '##potatoField', self.potato, -1)
    ... # more stuff
```

This way works fine for me, it initially shows "hello there" in the text field and I can change it to whatever else

**Comment by KinoxKlark** [comment]
There is `input_text_with_hint()` that already has the placeholder functionality. Hope this will help:

```python
changed, text_value = imgui.input_text_with_hint(
            'Email', 'your@email.com',
            text_value, -1)
```

**Comment by Darkratos** [comment]
> There is `input_text_with_hint()` that already has the placeholder functionality. Hope this will help:
> 
> ```python
> changed, text_value = imgui.input_text_with_hint(
>             'Email', 'your@email.com',
>             text_value, -1)
> ```

Oh my, I just came back using ImGui and I didn't realize they added it. Thank you so much!
