### ISSUE TITLE
Add support for font configs and custom glyph ranges

### ISSUE THREAD

**Issue by swistakm** [pyimgui/pyimgui#35]

**Comment by traverseda** [comment]
Is there an ETA for this? I'd very much like to be able to integrate some icon fonts into a project I'm working on.

**Comment by swistakm** [comment]
I’m currently a bit overloaded with work but I may find some time next month for this feature.

**Comment by dee909** [comment]
+1 
But, don't we already have glyph ranges with _StaticGlyphRanges ?

**Comment by zhihaoy** [comment]
The current pyimgui API does not allow customizing ranges. Therefore, without a predefined range, there is no way to render box-drawing characters https://en.m.wikipedia.org/wiki/Box_Drawing_(Unicode_block)

**Comment by DVD8084** [comment]
Any update on when this and #149 will be fixed?

**Comment by KinoxKlark** [comment]
This should be fixed thanks to @saulthu in #241. I merged the fix in branch `dev/version-2.0`. Let me know if there is any problem.
