### ISSUE TITLE
Can't import imgui when running in windows sandbox

### ISSUE THREAD

**Issue by pengumc** [pyimgui/pyimgui#356]
I'm getting the following error why trying to import imgui:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\WDAGUtilityAccount\AppData\Local\Programs\Python\Python311\Lib\site-packages\imgui\__init__.py", line 5, in <module>
    from imgui.core import *  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: DLL load failed while importing core: The specified module could not be found.
```

Steps to reproduce:
1. start a windows sandbox
2. install python 3.11
3. `pip install imgui`
4. open a python terminal and `import imgui`

I've also found that this behaviour is the same when trying to run in a hyper-V virtual machine. Running on real hardware or vmware virtual machines works fine with the exact same files.

**Comment by pengumc** [comment]
Culprit is a missing `Visual C++ Redistributable for Visual Studio 2015`  
installing form https://www.microsoft.com/en-us/download/details.aspx?id=48145 allows the DLL's to load properly

**Comment by learn-more** [comment]
Thanks for following this up.
