### ISSUE TITLE
Showing input text without a label

### ISSUE THREAD

**Issue by JC3** [pyimgui/pyimgui#360]
I'm rendering my own labels as text on the left side of text inputs.

How do I set a text input to not have a label?

I noticed that if I pass the same label (e.g. `""`) to every input text, then all the inputs duplicate eachother. It seems they have to have unique labels.

I couldn't find a text input flag to hide the label.

**Comment by learn-more** [comment]
For people stumbling on this and wondering what the solution is:
The same as in Dear Imgui itself:
* All labels need to have unique names (this is what Dear Imgui uses to identify them)
* Text after a double-hash `##` is not visible to the user, so if you want multiple 'empty' labels, name them like this:
  * `##label1`
  * `##label2`
  * Or better yet, more descriptive names.
