### ISSUE TITLE
default theme font

### ISSUE THREAD

**Issue by OscarMayReal** [pyimgui/pyimgui#366]
is it possible to change the default font (proggyclean.ttf) for all windows, like when you change the font through the style editor?

im using Python 3.12 on macOS 13.5 and the pygame renderer

**Comment by learn-more** [comment]
Have you tried `add_font_from_file_ttf` ?

**Comment by OscarMayReal** [comment]
yes, but it doesn't do everything I need, I need to change the font of every window, including the window titles

**Comment by learn-more** [comment]
`FontDefault` does not seem to be wrapped at the moment, so if `push_font` does not do what you want you'll have to patch pyimgui.

**Comment by OscarMayReal** [comment]
ok, I think I will switch to using Dear Pygui since that does appear to be mapped

thanks for the help!
