### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by FreePhoenix888** [pyimgui/pyimgui#372]
Example
```python
import imgui

# initilize imgui context (see documentation)
imgui.create_context()
imgui.get_io().display_size = 100, 100
imgui.get_io().fonts.get_tex_data_as_rgba32()

# start new frame context
imgui.new_frame()

# open new window context
imgui.begin("Your first window!", True)

# draw text label inside of current window
imgui.text("Hello world!")

# close current window context
imgui.end()

# pass all drawing comands to the rendering pipeline
# and close frame context
imgui.render()
imgui.end_frame()
```
from https://pyimgui.readthedocs.io/en/latest/guide/first-steps.html#basic-gui-drawing-loop is just not working. The program executes and exits with code 0:
```
Process finished with exit code 0
```

**Comment by learn-more** [comment]
> Of course this is not enough to create fully working GUI application with pyimgui. The bare [imgui.core](https://pyimgui.readthedocs.io/en/latest/reference/imgui.core.html#module-imgui.core) module is not able to render anything on its own. The imgui.render() function just passes abstract ImGui drawing commands to your rendering backend. In order to make it work you will first have to initialize the rendering backend of your choice.
